### ISSUE TITLE
toolchains support

### ISSUE THREAD

**Issue by sbartram** [takari/takari-lifecycle#16]
Will the lifecycle plugins (specifically the compiler) support toolchains?

**Comment by ifedorenko** [comment]
Can you provide more information what you are trying to do?

**Comment by sbartram** [comment]
I'm trying to use the lifecycle plugin with the maven-toolchains-plugin.
I'm running maven with java7 but I need to compile my code with java6.
Without the lifecycle plugin, it works fine.  When I enable the plugin, it
is apparently using java7 to compile instead of java6 which means it's not
"toolchains" aware.

**Comment by ifedorenko** [comment]
We have no plans to support java 6 and earlier at this point. You can still select java 6 compiler source/target, but you can't use actual java 6 compiler.

We may still need to do something about toolchains for better java 7+ support, but I will need to understand the usecase(s) before I can tell anything more specific.

**Comment by sbartram** [comment]
The fact that it's Java 6 is mostly irrelevant.  I could be running maven
with Java 8 and request the compiler to be Java 7.  That's what toolchains
is for.  So, I guess you are telling me that your compiler plugin isn't
toolchains aware.  The next question is are you planning to support it?
The standard maven-compiler-plugin (and most of the other Apache standard
plugins) are so it would seem to be rather important if you want to be
compatible.

**Comment by ifedorenko** [comment]
Again, the question is why you want to run with specific compiler instead of using compiler source/target. Just because maven-compiler-plugin supports toolchains does not mean takari compiler mojo needs to do the same. I know classes compiled against java 8 libraries may not run with java 7 is some cases, so this is one usecase. Do you know anything else?

Implementation-wise, there are currently three compiler "backends" implemented by takari lifecycle: javac, forked-javac and jdt. forked-javac backend can fully support toolchains and it is not possible to support toolchains with javac backed at all. With jdt compiler backend toolchains can only affect java system libraries used by the compiler but obviously not the compiler itself.

**Comment by sbartram** [comment]
Why?  2 answers:

1. Customer specific issue - I have to compile with Java 6 until we upgrade
certain dependencies.  I can't use maven 3.3+ with Java 6 but I can run it
with Java 7 (or 8) and tell it to compile with Java 6.  This works fine
without the takari-lifecycle plugin.

2. Common configuration and ease of tool management in large projects (1.5
million+ LOC, 50+ maven modules, 75+ developers)...

https://maven.apache.org/plugins/maven-toolchains-plugin/index.html

If you are not going to provide compatibility with the
maven-compiler-plugin, that's OK, we'll move on without it.  I was just
trying to improve our development environment and help you debug your
plugins at the same time.

**Comment by ifedorenko** [comment]
1. I already said we have no plans to support java 6.

2. Do you want to enforce the project is built against specific version of java or do you have other plugins that use toolchains?

**Comment by sbartram** [comment]
Again, it has nothing specifically to do with java 6.

These plugins all support toolchains:
http://maven.apache.org/guides/mini/guide-using-toolchains.html
